name: data_adapter_fine_test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python<3.13
  - fine<=2.4.1
  - pip
  - pip:
    - git+https://github.com/sedos-project/data_adapter@feature/store_foreign_data
