name: data_adapter_fine
dependencies:
  - conda-forge::python>=3.10
  - conda-forge::libiconv
  - conda-forge::gdal=3.4.3
  - conda-forge::geopandas
  - conda-forge::jupyter
  - conda-forge::notebook
  - conda-forge::libpysal
  - conda-forge::pip
  - conda-forge::descartes
  - conda-forge::glpk
  - conda-forge::openpyxl
  - conda-forge::matplotlib
  - conda-forge::xlrd
  - conda-forge::pyomo
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::networkx
  - conda-forge::scipy
  - conda-forge::scikit-learn>=1.2
  - conda-forge::xarray
  - conda-forge::rasterio
  - conda-forge::netcdf4
  - conda-forge::tsam
  - conda-forge::sphinx
  - conda-forge::sphinx_rtd_theme
  - conda-forge::myst-parser
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::nbval
  - conda-forge::black
  - conda-forge::pwlf
  - conda-forge::psutil
  - conda-forge::gurobi-logtools
  - pip:
     - -r requirements.txt
